<a href="https://colab.research.google.com/github/dordoran/Tugas-Data-Mining/blob/main/KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [26]:
dataset = pd.read_csv("data coba.csv")
x = dataset.iloc[:, [2,3]].values
y = dataset.iloc[:, -1].values

In [27]:
dataset.head()

id    kelamin  umur     gaji  membeli
0  3212       laki    23  2000000        1
1  3231  perempuan    32  3100000        0
2  3415       laki    41  4000000        1
3  3535  perempuan    22  3200000        0
4  4213       laki    31  2100000        0

In [28]:
x = dataset.iloc[:, [2,3]].values
y = dataset.iloc[:, -1].values

In [29]:
print(x)

[[     23 2000000]
 [     32 3100000]
 [     41 4000000]
 [     22 3200000]
 [     31 2100000]]


In [30]:
print(y)

[1 0 1 0 0]


In [31]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size = 0.25, random_state = 0)

In [32]:
print(x_train)

[[     32 3100000]
 [     22 3200000]
 [     31 2100000]]


In [33]:
len(x_train)

3

In [34]:
len(x)

5

In [35]:
len(x_test)

2

In [36]:
len(y)

5

In [37]:
len(y_test)

2

In [38]:
len(y_train)

3

In [39]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [40]:
print(x_train)

[[ 0.81537425  0.60404045]
 [-1.4083737   0.80538727]
 [ 0.59299945 -1.40942772]]


In [41]:
print(x_test)

[[ 2.8167474   2.4161618 ]
 [-1.18599891 -1.61077453]]


In [42]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p=2)
classifier.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [43]:
y_pred = classifier.predict(x_test)

ValueError: ignored

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

In [ ]:
from matplotlib.colors import ListedColormap
x_set, y_set = x_train, y_train
x1, x2 = np.meshgrid(np.arrange(start=x_set[:, 0].min()-1, stop=x_set[:,0].max()+1,step=0.01)
np. arrange(start=x_set[:, 1].min()-1,, stop=x_set[:,0].max()+1,step=0.01))
plt.contourf(x1,x2,classifier.predict(np.array([x1.ravel(),x2.ravel]).T).reshape(x1.shape),
             alpha = 0.75,cmap = ListedColormap(('red','green')))
plt.xlim(x1.min(), x1.max())
plt.ylim(x1.min(), x1.max())
for i,j in enumarate (np.uniqe(y_set)):
  plt scatter(x_set[y_set == j, 0],x_set[y_set == j, 1],
              c = ListedColormap(('red','green'))(i), label = j)
  plt.title('Klasifikasi data dengan K-NN (data mining)')
  plt.xlabel('umur')
  plt.ylabel('estimasi gaji')
  plt.lagend()
  plt.show()

In [ ]:
from matplotlib.colors import ListedColormap
x_set, y_set = x_test, y_test
x1, x2 = np.meshgrid(np.arrange(start=x_set[:, 0].min()-1, stop=x_set[:,0].max()+1,step=0.01)
np. arrange(start=x_set[:, 1].min()-1,, stop=x_set[:,0].max()+1,step=0.01))
plt.contourf(x1,x2,classifier.predict(np.array([x1.ravel(),x2.ravel]).T).reshape(x1.shape),
             alpha = 0.75,cmap = ListedColormap(('red','green')))
plt.xlim(x1.min(), x1.max())
plt.ylim(x1.min(), x1.max())
for i,j in enumarate (np.uniqe(y_set)):
  plt scatter(x_set[y_set == j, 0],x_set[y_set == j, 1],
              c = ListedColormap(('red','green'))(i), label = j)
  plt.title('Klasifikasi data dengan K-NN (data testing)')
  plt.xlabel('umur')
  plt.ylabel('estimasi gaji')
  plt.lagend()
  plt.show()